name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run smoke test
        run: |
          python - <<'PY'
          import app
          assert round(app.f_to_c(77), 2) == 25.00
          print("Smoke test OK")
          PY
